name: Update Problem Count

on:
  push:
    branches: [ main ]  # Change to your main branch name if different (e.g., master)
    paths-ignore:
      - 'README.md'     # Don't trigger when README itself is updated to avoid loops

jobs:
  update-count:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for better detection
    
    - name: Count problems and update README
      run: |
        # Count all files excluding .github directory, README.md, count_problems.py, stats.json and .git files
        count=$(find . -type f -not -path "./.git/*" -not -path "./.github/*" -not -name "README.md" -not -name "count_problems.py" -not -name "stats.json" -not -name ".gitignore" | wc -l)
        echo "Found $count problems"
        
        # Check if the count line already exists
        if grep -q "No. of Problems In This Repository:" README.md; then
          # Update existing count
          sed -i "s/No. of Problems In This Repository: [0-9]*/No. of Problems In This Repository: $count/" README.md
        else
          # Add new count line after the specified text
          sed -i "/If you find my solutions useful, consider star this repository (●'◡'●)/a\\\\nNo. of Problems In This Repository: $count" README.md
        fi
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Update problem count to $count"
        git push
